# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: EthosLink
email: hello@ethoslink.com
description: >- # this means to ignore newlines until "baseurl:"
  EthosLink builds AI-powered customer experience tools like Reviato so hospitality and service
  operators can understand feedback quickly and act with confidence.
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://www.ethos-link.com' # the base hostname & protocol for your site
twitter_username: thereviato
github_username: ethos-link

# Custom site data for the landing page
company:
  name: 'EthosLink'
  tagline: 'AI-Powered Customer Experience'
  description: 'We create approachable AI tools—like Reviato—that help hospitality businesses listen, learn, and respond to guests without extra stress.'

navigation:
  - name: 'Solutions'
    url: '/#solutions'
  - name: 'Portfolio'
    url: '/#portfolio'
  - name: 'About'
    url: '/about/'
  - name: 'Contact'
    url: '/contact/'

# Build settings
# theme: minima  # Commented out since using custom template
plugins:
  - jekyll-feed
  - jekyll-tailwindcss
  - jekyll-sitemap

# Include documentation files in the build
include:
  - docs/

# Defaults for documentation pages
defaults:
  - scope:
      path: "docs"
    values:
      sitemap: true
      layout: default

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
